Much work on packaging of xen stuff; not yet attempted a build

diff --git a/xen/readconfig.in b/xen/readconfig.in
--- a/xen/readconfig.in
+++ b/xen/readconfig.in
@@ -1,3 +1,72 @@
+# This bash script is sourced by the various tools to set the
+# adt_... variables and some other useful ones.
+
+#---------- useful general functions ----------
+
+fail () {
+	echo >&2 "xenlvm: ${0##*/}: error: $*"
+	exit 16
+}
+
+#---------- default values for simple settings ----------
+
+adt_nominum=adt
+adt_testbed_ram=256
+adt_freeze_ram=32
+adt_fs_size=1G
+adt_fs_snapsize=100M
+adt_fs_cowchunk=8
+adt_playbase=/var/lib/autopkgtest/xenlvm
+adt_fs_type=ext3
+adt_fs_mkfs_args=''
+adt_vm_reduce_retries=10
+adt_ssh_keytype=dsa
+
+adt_fw_localmirrors=''
+adt_fw_prohibnets='192.168.0.0/24 172.16.0.0/12 10.0.0.0/8'
+adt_fw_allowglobalports='80'
+
+adt_guest_macaddr=00:16:3e:7c:aa:7f
+adt_net_vifscript=/etc/xen/scripts/vif-route-adt
+
+#---------- arguments and config file ----------
+
+cmdline_args () {
+	while [ $# -gt 0 ]; do
+		arg="$1"
+		case "$arg" in
+		--*=*)
+			value="${arg#*=}"
+
+			var=${arg%%=*}
+			var=${var#--}
+			case "$var" in
+			*-*)	var="$(printf "%s" "$var" | tr -- - _)" ;;
+			esac
+			var=${var#adt_}
+
+			case $var in
+			*) ;; # @@varlist@@
+			*) fail "unknown configuration variable \`$var'" ;;
+			esac
+
+			eval "$var=\"\$value\""
+			shift ;;
+
+		--)	break ;;
+		-*)	fail "unknown option \`$arg'" ;;
+		*)	shift; break ;;
+		esac
+	done
+	test $# = 0 || fail "non-option arguments not allowed"
+}
+
+cmdline_args
+. ${adt_config}
+cmdline_args
+
+#---------- calculated defaults for complex settings ----------
+
 case "$adt_lvm_vg" in
 '')
 	echo "searching for default volume group ..."
@@ -112,3 +181,18 @@ ipaddr_from_hostname host
 
 : ${adt_fslink_dir:=adt-xenlvm}
 : ${adt_fslink_name:=${adt_nominum}_${adt_distro}_fs}
+
+# Firewall
+: ${adt_fw_testbedclients:=${adt_host_ipaddr}}
+
+lvm_baselv_namerhs=${adt_vg}/${adt_lvm_baselv}
+lvm_baselv_namepath=/dev/${adt_lvbaserhs}
+
+lvm_cowdata_namerhs:=${adt_vg}/${adt_lvm_cowdatalv}
+lvm_cowdata_namepath:=/dev/${lvm_cowdata_namerhs}
+
+lvm_snapdev=/dev/mapper/${adt_devmapper_cowdev}
+
+lvm_fslink_ptrrhs=${adt_fslink_dir}/${adt_fslink_name}
+lvm_fslink_dirpath=/dev/${adt_fslink_dir}
+lvm_fslink_ptr=/dev/${lvm_fslink_dir}/${adt_fslink_name}
