ssh-setup/adb: Guard adb wait-for-device with a 5 min timeout
LP: #1414939

diff --git a/ssh-setup/adb b/ssh-setup/adb
--- a/ssh-setup/adb
+++ b/ssh-setup/adb
@@ -150,7 +150,9 @@ EOF
 
 wait_booted() {
     echo "Waiting for device ADB to appear..." >&2
-    adb $ADBOPTS wait-for-device
+    if ! timeout 300 adb $ADBOPTS wait-for-device >/dev/null; then
+        echo "ERROR: Timed out waiting for adb device" >&2
+    fi
 }
 
 # configure Ubuntu device for testing
