ssh-setup/adb: Setup adb port forwarding again after rebooting

diff --git a/ssh-setup/adb b/ssh-setup/adb
--- a/ssh-setup/adb
+++ b/ssh-setup/adb
@@ -141,7 +141,7 @@ hostname=localhost
 port=$port
 capabilities=$CAPABILITIES
 identity=$IDENTITY
-extraopts=--no-reset
+extraopts=--no-reset --fwd-port=$port
 EOF
     if [ -n "$SUDO_PASSWORD" ]; then
         echo "password=$SUDO_PASSWORD"
@@ -245,8 +245,13 @@ revert() {
 }
 
 reboot() {
+    if [ -z "$FWD_PORT" ]; then
+        echo "ERROR: Must pass --fwd-port" >&2
+        exit 1
+    fi
     adb $ADBOPTS reboot
     wait_booted
+    adb $ADBOPTS forward tcp:$FWD_PORT tcp:22
     ubuntu_prepare_for_testing
 }
 
@@ -261,7 +266,7 @@ cleanup() {
 
 # argument parsing
 SHORTOPTS="l:,p:,s:,w,r,b"
-LONGOPTS="login:,password:,serial:,rw,apt-update,reset,reboot,no-reset"
+LONGOPTS="login:,password:,serial:,rw,apt-update,reset,reboot,no-reset,fwd-port:"
 
 TEMP=$(getopt -o $SHORTOPTS --long $LONGOPTS -- "$@")
 eval set -- "$TEMP"
@@ -290,6 +295,9 @@ while true; do
         --no-reset)
             RESET=""
             shift;;
+        --fwd-port)
+            FWD_PORT="$2"
+            shift 2;;
         --)
             shift;
             break;;
